# Generated by Django 5.2.17 on 2026-09-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_experience_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
