# Generated by Django 5.2.17 on 2026-09-21 13:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('programming', 'Programming Language'), ('framework', 'Framework & Library'), ('database', 'Database'), ('tool', 'Tool & Platform'), ('design', 'Design & Creative'), ('business', 'Business & Strategy'), ('soft-skill', 'Soft Skill')], default='programming', max_length=20)),
                ('proficiency', models.PositiveSmallIntegerField(choices=[(1, '1 - Beginner'), (2, '2 - Basic'), (3, '3 - Intermediate'), (4, '4 - Advanced'), (5, '5 - Expert')], default=3)),
                ('description', models.TextField(blank=True)),
                ('icon_url', models.URLField(blank=True, max_length=500)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', '-proficiency', 'name'],
            },
        ),
    ]
